### ISSUE TITLE
Document how to use phpDocumentor as github action

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2242]
In phpDocumentor's master branch a `action.yml` has been added. This opens new doors for projects to use phpDocumentor in their github workflows. The action is a currently a minimal setup. But no docs are available. 

We should add a page in our cookbook to explain how to use phpDocumentor in github actions.

**Comment by lightbulblighter** [comment]
@jaapio Hi, will this be added soon?

**Comment by thomascorthals** [comment]
A how-to would be much appreciated!

I've tried to get this minimal example working:

```yml
name: Run Tests

on:
    push:

jobs:
    run-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [7.4]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Generate API docs
              uses: phpDocumentor/phpDocumentor@master
              with:
                args: -d src -t build/docs
```

It *does* run on my local machine with `nektos/act`, but it fails when I push it to Github.

```
Current runner version: '2.285.1'
▸ Operating System
▸ Virtual Environment
▸ Virtual Environment Provisioner
▸ GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'shivammathur/setup-php@v2' (SHA:15b20027cf4e61cb21f2582a8f125cafb1c0492e)
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Download action repository 'phpDocumentor/phpDocumentor@master' (SHA:765c4dd50a0a1a425b6c3b8415d6b3f5e7c45df5)
Error: Could not find file '/home/runner/work/_actions/_temp_7b9dfe7a-b180-4190-9ff4-1d0b6474174f/_staging/phpDocumentor-phpDocumentor-765c4dd/bin/php-parse'.
```

**Comment by ryomo** [comment]
Hi, here is a minimal example 😄 

```yaml
name: phpDocumentor

on:
  push:
    branches: [ main ]

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d ./Src -t ./Docs

      - name: git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add Docs/
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push
```

**Comment by lkrms** [comment]
It took me so long to figure this out that I can't really justify writing it all up right now, but here's another solution (using parts of @ryomo's example above) that builds [this repo](https://github.com/lkrms/php-util) into [this GitHub Pages site](https://lkrms.github.io/php-util/) whenever there's a commit to `main`. You *should* be able to use it without even needing to explicitly enable GitHub Pages for the repo (the actions theoretically do this for you, but I've not tested it).

It also persists phpDocumentor's cache directory between runs, which might help with larger repos.

```yaml
name: documentation

on:
  push:
    branches: [main]

  # Allow running the workflow manually from the Actions tab
  #workflow_dispatch:

# Allow GITHUB_TOKEN to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v1
      - name: Cache phpDocumentor build files
        id: phpdocumentor-cache
        uses: actions/cache@v3
        with:
          path: .phpdoc/cache
          key: ${{ runner.os }}-phpdocumentor-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpdocumentor-
      - name: Build with phpDocumentor
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --target docs --cache-folder .phpdoc/cache --template default
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
