### ISSUE TITLE
Wrong Version of Documentation (My Fault)

### ISSUE THREAD

**Issue by oleibman** [phpDocumentor/phpDocumentor#3818]
There is nothing wrong with your product - this problem is my fault - but I wanted to ask if there were any "quick fixes" available. I am a maintainer for PhpOffice/PhpSpreadsheet. I recently pushed a security update to our main branch and several earlier branches which we continue to support, and tagged a new release for each. Had I done it correctly, all would be well, and the latest version of the docs would be available. But, I had a problem on one of the earlier branches, and needed to tag a new release for it. As a result, I believe the publicly available documentation now matches the most recently tagged branch rather than the main one. Is there anything I can do to bring it up to date apart from tagging a new release for the main branch?

For the long run, I would like to disable the documentation updates for the earlier branches. They all contain a file github-pages.yaml which starts as follows:
```
name: GithHub Pages
on:
  push:
    tags:
      - '*'
```
This is followed by steps to check out, set up, build the documentation, and deploy to Github pages. I am a little reluctant to delete the yaml file altogether. Would it lead to problems if I just commented out the deploy step? (I still want to run the build step just to make sure that it has no problems, but perhaps I'm over-thinking this.)

**Comment by oleibman** [comment]
Or might this do?
```
name: GithHub Pages
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
```

**Comment by jaapio** [comment]
We do publish our docs only on push to master. That might work for you as well.

**Comment by oleibman** [comment]
Sorry if I'm being obtuse - I'm a little gun-shy after the erroneous tag. Are you saying that you do more-or-less what I suggested in my second message?

**Comment by oleibman** [comment]
FWIW, I solved my problem on the non-current branches as follows:
```
name: GithHub Pages
on:
  push:
    branches:
      - 'master'
```
So pushes to the non-master branches never trigger this action, but the member exists in case I need to change it in future.
